using System;
using System.Collections.Generic;
using System.Text;

namespace MySubs.Domain.Common
{
    public static class TemplatesEmail
    {
        public static string GetNewUser()
        {
            StringBuilder sbEmail = new StringBuilder();

            sbEmail.Append("<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>");
            sbEmail.Append("<html>");
            sbEmail.Append("<head>");
            sbEmail.Append("  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>");
            sbEmail.Append("  <meta name='viewport' content='width=device-width, initial-scale=1.0' />");
            sbEmail.Append("  <title>Instamore</title>");
            sbEmail.Append("  <style type='text/css'>");
            sbEmail.Append("    body,");
            sbEmail.Append("    #body_style {");
            sbEmail.Append("      margin: 0;");
            sbEmail.Append("      padding: 0;");
            sbEmail.Append("      background: #f1f1f1;");
            sbEmail.Append("      color: #5b656e;");
            sbEmail.Append("    }");
            sbEmail.Append("    a {");
            sbEmail.Append("      color: #09c;");
            sbEmail.Append("    }");
            sbEmail.Append("    a img {");
            sbEmail.Append("      border: none;");
            sbEmail.Append("      text-decoration: none;");
            sbEmail.Append("    }");
            sbEmail.Append("    table,");
            sbEmail.Append("    table td {");
            sbEmail.Append("      border-collapse: collapse;");
            sbEmail.Append("    }");
            sbEmail.Append("    td,");
            sbEmail.Append("    h1,");
            sbEmail.Append("    h2,");
            sbEmail.Append("    h3,");
            sbEmail.Append("    p {");
            sbEmail.Append("      font-family: arial, helvetica, sans-serif;");
            sbEmail.Append("      color: #313a42;");
            sbEmail.Append("    }");
            sbEmail.Append("    h1,");
            sbEmail.Append("    h2,");
            sbEmail.Append("    h3,");
            sbEmail.Append("    h4 {");
            sbEmail.Append("      color: #313a42 !important;");
            sbEmail.Append("      font-weight: normal;");
            sbEmail.Append("      line-height: 1.2;");
            sbEmail.Append("    }");
            sbEmail.Append("    h1 {");
            sbEmail.Append("      font-size: 24px;");
            sbEmail.Append("    }");
            sbEmail.Append("    h2 {");
            sbEmail.Append("      font-size: 18px;");
            sbEmail.Append("    }");
            sbEmail.Append("    h3 {");
            sbEmail.Append("      font-size: 16px;");
            sbEmail.Append("    }");
            sbEmail.Append("    p {");
            sbEmail.Append("      margin: 0 0 1.6em 0;");
            sbEmail.Append("    }");
            sbEmail.Append("    .gradient {");
            sbEmail.Append("      background-image: url('https://i.ibb.co/JQ9xRB4/gradient.png');");
            sbEmail.Append("      background-repeat: repeat-x;");
            sbEmail.Append("    }");
            sbEmail.Append("    #outlook a {");
            sbEmail.Append("      padding: 0;");
            sbEmail.Append("    }");
            sbEmail.Append("    .preheader {");
            sbEmail.Append("      background-color: #f6f6f6;");
            sbEmail.Append("    }");
            sbEmail.Append("    .preheaderContent,");
            sbEmail.Append("    .webversion,");
            sbEmail.Append("    .webversion a {");
            sbEmail.Append("      color: #999999;");
            sbEmail.Append("      font-size: 10px;");
            sbEmail.Append("      padding-left: 5px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .preheaderContent {");
            sbEmail.Append("      width: 440px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .preheaderContent,");
            sbEmail.Append("    .webversion {");
            sbEmail.Append("      padding: 5px 10px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .webversion {");
            sbEmail.Append("      width: 300px;");
            sbEmail.Append("      text-align: right;");
            sbEmail.Append("    }");
            sbEmail.Append("    .webversion a {");
            sbEmail.Append("      text-decoration: underline;");
            sbEmail.Append("      color: #999999;");
            sbEmail.Append("      font-size: 10px;");
            sbEmail.Append("      padding-left: 5px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .logoContainer {");
            sbEmail.Append("      padding: 20px 0 10px 0px;");
            sbEmail.Append("      width: 320px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .logoContainer a {");
            sbEmail.Append("      color: #ffffff;");
            sbEmail.Append("    }");
            sbEmail.Append("    .whitespace {");
            sbEmail.Append("      font-family: 0px;");
            sbEmail.Append("      line-height: 0px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .buttonContainer {");
            sbEmail.Append("      padding: 10px 20px 10px 20px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .button a {");
            sbEmail.Append("      text-decoration: none;");
            sbEmail.Append("      display: block;");
            sbEmail.Append("      text-transform: uppercase;");
            sbEmail.Append("      color: white !important;");
            sbEmail.Append("    }");
            sbEmail.Append("    .featuredHeader {");
            sbEmail.Append("      background: #556270;");
            sbEmail.Append("    }");
            sbEmail.Append("    #featuredImage img {");
            sbEmail.Append("      display: block;");
            sbEmail.Append("      margin: 0 auto;");
            sbEmail.Append("    }");
            sbEmail.Append("    .featuredTitle {");
            sbEmail.Append("      color: #ffffff;");
            sbEmail.Append("      font-size: 26px;");
            sbEmail.Append("      padding: 0px 0px 10px 0px;");
            sbEmail.Append("      font-weight: bold;");
            sbEmail.Append("    }");
            sbEmail.Append("    .featuredContent {");
            sbEmail.Append("      color: #ffffff;");
            sbEmail.Append("    }");
            sbEmail.Append("    .section {");
            sbEmail.Append("      padding: 20px 0px 0px 0px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionOdd {");
            sbEmail.Append("      background-color: #f1f1f1;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionEven {");
            sbEmail.Append("      background-color: #ffffff;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionOdd,");
            sbEmail.Append("    .sectionEven {");
            sbEmail.Append("      padding: 30px 0px 30px 0px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionArticleTitle,");
            sbEmail.Append("    .sectionArticleContent {");
            sbEmail.Append("      text-align: center;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionArticleTitle {");
            sbEmail.Append("      font-size: 18px;");
            sbEmail.Append("      padding: 10px 0px 5px;");
            sbEmail.Append("      0px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionArticleContent {");
            sbEmail.Append("      font-size: 13px;");
            sbEmail.Append("      line-height: 18px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionArticleImage {");
            sbEmail.Append("      text-align: center;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionArticleImage img {");
            sbEmail.Append("      padding: 0px 0px 0px 0px;");
            sbEmail.Append("      -ms-interpolation-mode: bicubic;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionTitle,");
            sbEmail.Append("    .sectionSubTitle {");
            sbEmail.Append("      text-align: center;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionTitle {");
            sbEmail.Append("      font-size: 26px;");
            sbEmail.Append("      padding: 0px 10px 10px 10px");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionSubTitle {");
            sbEmail.Append("      padding: 0px 10px 20px 10px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .footNotes {");
            sbEmail.Append("      padding: 0px 20px 0px 20px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .footNotes a {");
            sbEmail.Append("      color: #556270;");
            sbEmail.Append("      font-size: 13px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .button {");
            sbEmail.Append("      background-image: url('https://i.ibb.co/5kCPNY0/button-gradient.png');");
            sbEmail.Append("      background-repeat: repeat-x;");
            sbEmail.Append("      padding: 10px 5px 10px 5px;");
            sbEmail.Append("      text-align: center;");
            sbEmail.Append("      border-radius: 4px;");
            sbEmail.Append("      color: white !important;");
            sbEmail.Append("    }");
            sbEmail.Append("    .socialMedia {");
            sbEmail.Append("      height: 65px;");
            sbEmail.Append("      background-image: url('https://i.ibb.co/0GJpq5d/gradient-social-media.png');");
            sbEmail.Append("      background-repeat: repeat-x;");
            sbEmail.Append("    }");
            sbEmail.Append("    img.logo {");
            sbEmail.Append("      width: 179px;");
            sbEmail.Append("      height: 48px;");
            sbEmail.Append("    }");
            sbEmail.Append("    @media only screen and (max-width: 1280px) {");
            sbEmail.Append("      .container-featured {");
            sbEmail.Append("        margin-left: 10px !important;");
            sbEmail.Append("      }");
            sbEmail.Append("      .preheader {");
            sbEmail.Append("        display: none;");
            sbEmail.Append("      }");
            sbEmail.Append("    }");
            sbEmail.Append("    @media only screen and (max-width: 480px) {");
            sbEmail.Append("      body,");
            sbEmail.Append("      table,");
            sbEmail.Append("      td,");
            sbEmail.Append("      p,");
            sbEmail.Append("      a,");
            sbEmail.Append("      li,");
            sbEmail.Append("      blockquote {");
            sbEmail.Append("        -webkit-text-size-adjust: none !important;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] table {");
            sbEmail.Append("        width: 100% !important;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .webversion {");
            sbEmail.Append("        display: none;");
            sbEmail.Append("        font-size: 0;");
            sbEmail.Append("        max-height: 0;");
            sbEmail.Append("        line-height: 0;");
            sbEmail.Append("        mso-hide: all;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .logoContainer,");
            sbEmail.Append("      body[yahoofix] .featuredTitle,");
            sbEmail.Append("      body[yahoofix] .featuredContent {");
            sbEmail.Append("        text-align: center;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .sectionArticleImage img {");
            sbEmail.Append("        height: auto !important;");
            sbEmail.Append("        max-width: 100% !important;");
            sbEmail.Append("      }");
            sbEmail.Append("      .preheader {");
            sbEmail.Append("        display: none;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .preheaderContent {");
            sbEmail.Append("        text-align: center;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .buttonContainer {");
            sbEmail.Append("        padding: 0px 20px 0px 20px;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .column {");
            sbEmail.Append("        float: left;");
            sbEmail.Append("        width: 100%;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] #featuredImage {");
            sbEmail.Append("        text-align: center;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .featuredTitle {");
            sbEmail.Append("        line-height: 24px;");
            sbEmail.Append("        font-weight: normal !important;");
            sbEmail.Append("        padding: 0px 10px 25px 10px;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .featuredContent {");
            sbEmail.Append("        padding: 0px 10px 20px 10px;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .sectionArticleTitle {");
            sbEmail.Append("        padding: 0px 10px 0px 10px !important;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .sectionArticleContent {");
            sbEmail.Append("        padding: 0px 10px 30px 10px !important;");
            sbEmail.Append("      }");
            sbEmail.Append("    }");
            sbEmail.Append("  </style>");
            sbEmail.Append("</head>");
            sbEmail.Append("<body yahoofix>");
            sbEmail.Append("  <span id='body_style' style='display:block'>");
            sbEmail.Append("    <table class='preheader' cellpadding='0' cellspacing='0' width='100%'>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td>");
            sbEmail.Append("          <table border='0' cellpadding='0' cellspacing='0' summary='' width='640' align='center'>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td class='preheaderContent'>Venha dar um boost em seu Instagram...</td>");
            sbEmail.Append("              <td class='webversion'>Está esperando o quê?<a href='https://www.instamore.com.br/'");
            sbEmail.Append("                  title='View the webversion'>Garanta já nossos serviços</a></td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("    <table border='0' cellspacing='0' cellpadding='0' width='100%' summary='' class='topHeader'>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td>");
            sbEmail.Append("          <table border='0' cellspacing='0' cellpadding='0' width='640' align='center' summary=''>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td class='logoContainer' align='center'>");
            sbEmail.Append("                <a href='https://www.instamore.com.br/' title='Lorem logo'>");
            sbEmail.Append("                  <img class='logo' src='https://i.ibb.co/9Vsj0rm/Logo2.png' alt='Lorem logo' />");
            sbEmail.Append("                </a>");
            sbEmail.Append("              </td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("    <table border='0' cellspacing='0' cellpadding='0' width='100%' summary='' class='gradient'>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='section'>");
            sbEmail.Append("          <table border='0' cellspacing='0' cellpadding='0' width='640' align='center' summary=''>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td class='column'>");
            sbEmail.Append("                <table border='0' cellspacing='0' cellpadding='0' width='395' summary='' class='container-featured'>");
            sbEmail.Append("                  <tr>");
            sbEmail.Append("                    <td class='featuredTitle'>");
            sbEmail.Append("                        O primeiro passo foi dado!");
            sbEmail.Append("                    </td>");
            sbEmail.Append("                  </tr>");
            sbEmail.Append("                  <tr>");
            sbEmail.Append("                    <td class='featuredContent'>");
            sbEmail.Append("                     Você realmente demonstra ter um interesse real em crescer e melhorar seus resultados.");
            sbEmail.Append("                    </td>");
            sbEmail.Append("                  </tr>");
            sbEmail.Append("                </table>");
            sbEmail.Append("              </td>");
            sbEmail.Append("              <td id='featuredImage' class='column'><img src='https://i.ibb.co/qnsM2pz/mobile-phone.png' width='234'");
            sbEmail.Append("                  alt='' /></td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("    <table border='0' cellpadding='0' cellspacing='0' width='100%' summary=''>");
            sbEmail.Append("        <tr>");
            sbEmail.Append("          <td class='sectionOdd'>");
            sbEmail.Append("            <table border='0' cellpadding='0' cellspacing='0' width='640' align='center' summary=''>");
            sbEmail.Append("              <tr>");
            sbEmail.Append("                <td class='column' valign='top'>");
            sbEmail.Append("                  <table border='0' cellpadding='0' cellspacing='0' width='100%' align='left' summary=''>");
            sbEmail.Append("                    <tr>");
            sbEmail.Append("                      <td class='sectionArticleContent'>Agora vem a parte mais fácil na busca por seus resultados mas não menos importante. Preste atenção abaixo:");
            sbEmail.Append("                          VOCÊ FOI DOS GANHADORES DA NOSSA <b>PROMOÇÃO</b>: SÃO 15 DIAS GRATUITOS PARA UTILIZAÇÃO DE NOSSA FERRAMENTA DE RESULTADOS!");
            sbEmail.Append("                          Quer saber como funciona? ");
            sbEmail.Append("                          É <b>fácil</b>!");
            sbEmail.Append("                          Acesse o link a seguir e siga nossos passos e instruções para começar a utilizar nossa plataforma: <a href='https://app.instamore.com.br' target='_blank'>https://app.instamore.com.br</a>");
            sbEmail.Append("                          ");
            sbEmail.Append("                          Se você não é o dono dessa conta, favor desconsiderar este e-mail.");
            sbEmail.Append("                          Esse é um e-mail automático, não responda.</td>");
            sbEmail.Append("                    </tr>");
            sbEmail.Append("                  </table>");
            sbEmail.Append("                </td>");
            sbEmail.Append("              </tr>");
            sbEmail.Append("            </table>");
            sbEmail.Append("          </td>");
            sbEmail.Append("        </tr>");
            sbEmail.Append("      </table>");
            sbEmail.Append("    <table border='0' cellspacing='0' cellpadding='0' width='100%' summary='' class='socialMedia'>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='whitespace' height='10'>&nbsp;</td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td>");
            sbEmail.Append("          <table border='0' cellspacing='0' cellpadding='0' width='120' align='center' summary=''>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td align='center' width='32'>");
            sbEmail.Append("                <a href='https://www.instagram.com/instamoreoficial/?hl=pt-br' title='Instagram' target='_blank'><img");
            sbEmail.Append("                    src='https://i.ibb.co/mhMYPSF/instagram-icon.png' width='38' alt='Instagram' /></a>");
            sbEmail.Append("              </td>");
            sbEmail.Append("              <td align='center' width='32'>");
            sbEmail.Append("                <a href='#' title='Youtube'><img src='https://i.ibb.co/Ny10z3J/youtube3-icon.png' width='45'");
            sbEmail.Append("                    alt='Youtube' /></a>");
            sbEmail.Append("              </td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='whitespace' height='10'>&nbsp;</td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("    <table border='0' cellspacing='0' cellpadding='0' width='100%' summary='' class='footer'>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='whitespace' height='10'>&nbsp;</td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td>");
            sbEmail.Append("          <table border='0' cellspacing='0' cellpadding='0' width='120' align='center' summary=''>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td class='footNotes' align='center'>");
            sbEmail.Append("                <a href='#' title='Unsubscribe'>Cancelar inscrição</a>");
            sbEmail.Append("              </td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='whitespace' height='10'>&nbsp;</td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("  </span>");
            sbEmail.Append("</body>");
            sbEmail.Append("</html>");

            return sbEmail.ToString();
        }

        public static string GetForgotPassword()
        {
            StringBuilder sbEmail = new StringBuilder();

            sbEmail.Append("<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>");
            sbEmail.Append("<html>");
            sbEmail.Append("<head>");
            sbEmail.Append("  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>");
            sbEmail.Append("  <meta name='viewport' content='width=device-width, initial-scale=1.0' />");
            sbEmail.Append("  <title>Instamore</title>");
            sbEmail.Append("  <style type='text/css'>");
            sbEmail.Append("    body,");
            sbEmail.Append("    #body_style {");
            sbEmail.Append("      margin: 0;");
            sbEmail.Append("      padding: 0;");
            sbEmail.Append("      background: #f1f1f1;");
            sbEmail.Append("      color: #5b656e;");
            sbEmail.Append("    }");
            sbEmail.Append("    a {");
            sbEmail.Append("      color: #09c;");
            sbEmail.Append("    }");
            sbEmail.Append("    a img {");
            sbEmail.Append("      border: none;");
            sbEmail.Append("      text-decoration: none;");
            sbEmail.Append("    }");
            sbEmail.Append("    table,");
            sbEmail.Append("    table td {");
            sbEmail.Append("      border-collapse: collapse;");
            sbEmail.Append("    }");
            sbEmail.Append("    td,");
            sbEmail.Append("    h1,");
            sbEmail.Append("    h2,");
            sbEmail.Append("    h3,");
            sbEmail.Append("    p {");
            sbEmail.Append("      font-family: arial, helvetica, sans-serif;");
            sbEmail.Append("      color: #313a42;");
            sbEmail.Append("    }");
            sbEmail.Append("    h1,");
            sbEmail.Append("    h2,");
            sbEmail.Append("    h3,");
            sbEmail.Append("    h4 {");
            sbEmail.Append("      color: #313a42 !important;");
            sbEmail.Append("      font-weight: normal;");
            sbEmail.Append("      line-height: 1.2;");
            sbEmail.Append("    }");
            sbEmail.Append("    h1 {");
            sbEmail.Append("      font-size: 24px;");
            sbEmail.Append("    }");
            sbEmail.Append("    h2 {");
            sbEmail.Append("      font-size: 18px;");
            sbEmail.Append("    }");
            sbEmail.Append("    h3 {");
            sbEmail.Append("      font-size: 16px;");
            sbEmail.Append("    }");
            sbEmail.Append("    p {");
            sbEmail.Append("      margin: 0 0 1.6em 0;");
            sbEmail.Append("    }");
            sbEmail.Append("    .gradient {");
            sbEmail.Append("      background-image: url('https://i.ibb.co/JQ9xRB4/gradient.png');");
            sbEmail.Append("      background-repeat: repeat-x;");
            sbEmail.Append("    }");
            sbEmail.Append("    #outlook a {");
            sbEmail.Append("      padding: 0;");
            sbEmail.Append("    }");
            sbEmail.Append("    .preheader {");
            sbEmail.Append("      background-color: #f6f6f6;");
            sbEmail.Append("    }");
            sbEmail.Append("    .preheaderContent,");
            sbEmail.Append("    .webversion,");
            sbEmail.Append("    .webversion a {");
            sbEmail.Append("      color: #999999;");
            sbEmail.Append("      font-size: 10px;");
            sbEmail.Append("      padding-left: 5px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .preheaderContent {");
            sbEmail.Append("      width: 440px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .preheaderContent,");
            sbEmail.Append("    .webversion {");
            sbEmail.Append("      padding: 5px 10px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .webversion {");
            sbEmail.Append("      width: 300px;");
            sbEmail.Append("      text-align: right;");
            sbEmail.Append("    }");
            sbEmail.Append("    .webversion a {");
            sbEmail.Append("      text-decoration: underline;");
            sbEmail.Append("      color: #999999;");
            sbEmail.Append("      font-size: 10px;");
            sbEmail.Append("      padding-left: 5px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .logoContainer {");
            sbEmail.Append("      padding: 20px 0 10px 0px;");
            sbEmail.Append("      width: 320px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .logoContainer a {");
            sbEmail.Append("      color: #ffffff;");
            sbEmail.Append("    }");
            sbEmail.Append("    .whitespace {");
            sbEmail.Append("      font-family: 0px;");
            sbEmail.Append("      line-height: 0px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .buttonContainer {");
            sbEmail.Append("      padding: 10px 20px 10px 20px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .button a {");
            sbEmail.Append("      text-decoration: none;");
            sbEmail.Append("      display: block;");
            sbEmail.Append("      text-transform: uppercase;");
            sbEmail.Append("      color: white !important;");
            sbEmail.Append("    }");
            sbEmail.Append("    .featuredHeader {");
            sbEmail.Append("      background: #556270;");
            sbEmail.Append("    }");
            sbEmail.Append("    #featuredImage img {");
            sbEmail.Append("      display: block;");
            sbEmail.Append("      margin: 0 auto;");
            sbEmail.Append("    }");
            sbEmail.Append("    .featuredTitle {");
            sbEmail.Append("      color: #ffffff;");
            sbEmail.Append("      font-size: 26px;");
            sbEmail.Append("      padding: 0px 0px 10px 0px;");
            sbEmail.Append("      font-weight: bold;");
            sbEmail.Append("    }");
            sbEmail.Append("    .featuredContent {");
            sbEmail.Append("      color: #ffffff;");
            sbEmail.Append("    }");
            sbEmail.Append("    .section {");
            sbEmail.Append("      padding: 20px 0px 0px 0px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionOdd {");
            sbEmail.Append("      background-color: #f1f1f1;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionEven {");
            sbEmail.Append("      background-color: #ffffff;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionOdd,");
            sbEmail.Append("    .sectionEven {");
            sbEmail.Append("      padding: 30px 0px 30px 0px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionArticleTitle,");
            sbEmail.Append("    .sectionArticleContent {");
            sbEmail.Append("      text-align: center;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionArticleTitle {");
            sbEmail.Append("      font-size: 18px;");
            sbEmail.Append("      padding: 10px 0px 5px;");
            sbEmail.Append("      0px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionArticleContent {");
            sbEmail.Append("      font-size: 13px;");
            sbEmail.Append("      line-height: 18px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionArticleImage {");
            sbEmail.Append("      text-align: center;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionArticleImage img {");
            sbEmail.Append("      padding: 0px 0px 0px 0px;");
            sbEmail.Append("      -ms-interpolation-mode: bicubic;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionTitle,");
            sbEmail.Append("    .sectionSubTitle {");
            sbEmail.Append("      text-align: center;");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionTitle {");
            sbEmail.Append("      font-size: 26px;");
            sbEmail.Append("      padding: 0px 10px 10px 10px");
            sbEmail.Append("    }");
            sbEmail.Append("    .sectionSubTitle {");
            sbEmail.Append("      padding: 0px 10px 20px 10px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .footNotes {");
            sbEmail.Append("      padding: 0px 20px 0px 20px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .footNotes a {");
            sbEmail.Append("      color: #556270;");
            sbEmail.Append("      font-size: 13px;");
            sbEmail.Append("    }");
            sbEmail.Append("    .button {");
            sbEmail.Append("      background-image: url('https://i.ibb.co/5kCPNY0/button-gradient.png');");
            sbEmail.Append("      background-repeat: repeat-x;");
            sbEmail.Append("      padding: 10px 5px 10px 5px;");
            sbEmail.Append("      text-align: center;");
            sbEmail.Append("      border-radius: 4px;");
            sbEmail.Append("      color: white !important;");
            sbEmail.Append("    }");
            sbEmail.Append("    .socialMedia {");
            sbEmail.Append("      height: 65px;");
            sbEmail.Append("      background-image: url('https://i.ibb.co/0GJpq5d/gradient-social-media.png');");
            sbEmail.Append("      background-repeat: repeat-x;");
            sbEmail.Append("    }");
            sbEmail.Append("    img.logo {");
            sbEmail.Append("      width: 179px;");
            sbEmail.Append("      height: 48px;");
            sbEmail.Append("    }");
            sbEmail.Append("    @media only screen and (max-width: 1280px) {");
            sbEmail.Append("      .container-featured {");
            sbEmail.Append("        margin-left: 10px !important;");
            sbEmail.Append("      }");
            sbEmail.Append("      .preheader {");
            sbEmail.Append("        display: none;");
            sbEmail.Append("      }");
            sbEmail.Append("    }");
            sbEmail.Append("    @media only screen and (max-width: 480px) {");
            sbEmail.Append("      body,");
            sbEmail.Append("      table,");
            sbEmail.Append("      td,");
            sbEmail.Append("      p,");
            sbEmail.Append("      a,");
            sbEmail.Append("      li,");
            sbEmail.Append("      blockquote {");
            sbEmail.Append("        -webkit-text-size-adjust: none !important;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] table {");
            sbEmail.Append("        width: 100% !important;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .webversion {");
            sbEmail.Append("        display: none;");
            sbEmail.Append("        font-size: 0;");
            sbEmail.Append("        max-height: 0;");
            sbEmail.Append("        line-height: 0;");
            sbEmail.Append("        mso-hide: all;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .logoContainer,");
            sbEmail.Append("      body[yahoofix] .featuredTitle,");
            sbEmail.Append("      body[yahoofix] .featuredContent {");
            sbEmail.Append("        text-align: center;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .sectionArticleImage img {");
            sbEmail.Append("        height: auto !important;");
            sbEmail.Append("        max-width: 100% !important;");
            sbEmail.Append("      }");
            sbEmail.Append("      .preheader {");
            sbEmail.Append("        display: none;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .preheaderContent {");
            sbEmail.Append("        text-align: center;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .buttonContainer {");
            sbEmail.Append("        padding: 0px 20px 0px 20px;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .column {");
            sbEmail.Append("        float: left;");
            sbEmail.Append("        width: 100%;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] #featuredImage {");
            sbEmail.Append("        text-align: center;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .featuredTitle {");
            sbEmail.Append("        line-height: 24px;");
            sbEmail.Append("        font-weight: normal !important;");
            sbEmail.Append("        padding: 0px 10px 25px 10px;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .featuredContent {");
            sbEmail.Append("        padding: 0px 10px 20px 10px;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .sectionArticleTitle {");
            sbEmail.Append("        padding: 0px 10px 0px 10px !important;");
            sbEmail.Append("      }");
            sbEmail.Append("      body[yahoofix] .sectionArticleContent {");
            sbEmail.Append("        padding: 0px 10px 30px 10px !important;");
            sbEmail.Append("      }");
            sbEmail.Append("    }");
            sbEmail.Append("  </style>");
            sbEmail.Append("</head>");
            sbEmail.Append("<body yahoofix>");
            sbEmail.Append("  <span id='body_style' style='display:block'>");
            sbEmail.Append("    <table class='preheader' cellpadding='0' cellspacing='0' width='100%'>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td>");
            sbEmail.Append("          <table border='0' cellpadding='0' cellspacing='0' summary='' width='640' align='center'>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td class='preheaderContent'>Venha dar um boost em seu Instagram...</td>");
            sbEmail.Append("              <td class='webversion'>Está esperando o quê?<a href='https://www.instamore.com.br/'");
            sbEmail.Append("                  title='View the webversion'>Garanta já nossos serviços</a></td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("    <table border='0' cellspacing='0' cellpadding='0' width='100%' summary='' class='topHeader'>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td>");
            sbEmail.Append("          <table border='0' cellspacing='0' cellpadding='0' width='640' align='center' summary=''>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td class='logoContainer' align='center'>");
            sbEmail.Append("                <a href='https://www.instamore.com.br/' title='Lorem logo'>");
            sbEmail.Append("                  <img class='logo' src='https://i.ibb.co/9Vsj0rm/Logo2.png' alt='Lorem logo' />");
            sbEmail.Append("                </a>");
            sbEmail.Append("              </td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("    <table border='0' cellspacing='0' cellpadding='0' width='100%' summary='' class='gradient'>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='section'>");
            sbEmail.Append("          <table border='0' cellspacing='0' cellpadding='0' width='640' align='center' summary=''>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td class='column'>");
            sbEmail.Append("                <table border='0' cellspacing='0' cellpadding='0' width='395' summary='' class='container-featured'>");
            sbEmail.Append("                  <tr>");
            sbEmail.Append("                    <td class='featuredTitle'>");
            sbEmail.Append("                        Nova senha temporária.");
            sbEmail.Append("                    </td>");
            sbEmail.Append("                  </tr>");
            sbEmail.Append("                  <tr>");
            sbEmail.Append("                    <td class='featuredContent'>");
            sbEmail.Append("                      Olá {{name}}, já dizia minha mãe, só não esquece a cabeça porque ta grudada no pescoço 😊.");
            sbEmail.Append("                      Chega de sofrer utilize sua senha temporária e volte a ter acesso a nossa ferramenta de RESULTADOS! 😊");
            sbEmail.Append("                    </td>");
            sbEmail.Append("                  </tr>");
            sbEmail.Append("                </table>");
            sbEmail.Append("              </td>");
            sbEmail.Append("              <td id='featuredImage' class='column'><img src='https://i.ibb.co/qnsM2pz/mobile-phone.png' width='234'");
            sbEmail.Append("                  alt='' /></td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("    ");
            sbEmail.Append("    <table border='0' cellpadding='0' cellspacing='0' width='100%' summary=''>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='sectionEven'>");
            sbEmail.Append("          <table border='0' cellpadding='0' cellspacing='0' width='640' align='center' summary=''>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td class='sectionTitle'>Senha: {{password}}</td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td class='buttonContainer'>");
            sbEmail.Append("                <table border='0' cellpadding='0' cellspacing='0' summary='' width='30%' align='center'>");
            sbEmail.Append("                  <tr>");
            sbEmail.Append("                    <td class='button'><a href='https://app.instamore.com.br' target='_blank' title='ipsum'>Acessar</a></td>");
            sbEmail.Append("                  </tr>");
            sbEmail.Append("                 </table>");
            sbEmail.Append("              </td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("    <table border='0' cellspacing='0' cellpadding='0' width='100%' summary='' class='socialMedia'>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='whitespace' height='10'>&nbsp;</td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td>");
            sbEmail.Append("          <table border='0' cellspacing='0' cellpadding='0' width='120' align='center' summary=''>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td align='center' width='32'>");
            sbEmail.Append("                <a href='https://www.instagram.com/instamoreoficial/?hl=pt-br' title='Instagram' target='_blank'><img");
            sbEmail.Append("                    src='https://i.ibb.co/mhMYPSF/instagram-icon.png' width='38' alt='Instagram' /></a>");
            sbEmail.Append("              </td>");
            sbEmail.Append("              <td align='center' width='32'>");
            sbEmail.Append("                <a href='#' title='Youtube'><img src='https://i.ibb.co/Ny10z3J/youtube3-icon.png' width='45'");
            sbEmail.Append("                    alt='Youtube' /></a>");
            sbEmail.Append("              </td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='whitespace' height='10'>&nbsp;</td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("    <table border='0' cellspacing='0' cellpadding='0' width='100%' summary='' class='footer'>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='whitespace' height='10'>&nbsp;</td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td>");
            sbEmail.Append("          <table border='0' cellspacing='0' cellpadding='0' width='120' align='center' summary=''>");
            sbEmail.Append("            <tr>");
            sbEmail.Append("              <td class='footNotes' align='center'>");
            sbEmail.Append("                <a href='#' title='Unsubscribe'>Cancelar inscrição</a>");
            sbEmail.Append("              </td>");
            sbEmail.Append("            </tr>");
            sbEmail.Append("          </table>");
            sbEmail.Append("        </td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("      <tr>");
            sbEmail.Append("        <td class='whitespace' height='10'>&nbsp;</td>");
            sbEmail.Append("      </tr>");
            sbEmail.Append("    </table>");
            sbEmail.Append("  </span>");
            sbEmail.Append("</body>");
            sbEmail.Append("</html>");

            return sbEmail.ToString();
        }
    }
}
