CREATE TABLE Users
(
	Id INT IDENTITY(1,1) NOT NULL  PRIMARY KEY,
	Name VARCHAR(250) NOT NULL,
	Email VARCHAR(250) NOT NULL,
	Password VARCHAR(MAX) NOT NULL,
	ProfilePicture VARCHAR(MAX),
	AcceptTermsOfUse BIT NOT NULL,
	DateAcceptTermsOfUse DATETIME NOT NULL,
	Active BIT NOT NULL,
);

