CREATE TABLE "MySubs"
(
	Id BIGINT IDENTITY(1,1) NOT NULL  PRIMARY KEY,
	IdUser BIGINT NOT NULL,
	IdService BIGINT NOT NULL,
	IdPlanType BIGINT NOT NULL,
	Price FLOAT,
	CancelRenewal BIT NOT NULL,
	DateSignature DATETIME,
	Active BIT NOT NULL,
);